package docs

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"
)

// RegenerateIndexes rebuilds _index.md files for the entire docs directory tree recursively.
func RegenerateIndexes(docsDir string) error {
	if err := writeRootIndex(docsDir); err != nil {
		return fmt.Errorf("root index: %w", err)
	}
	return filepath.WalkDir(docsDir, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() || path == docsDir || strings.HasPrefix(d.Name(), ".") {
			return nil
		}
		if err := writeIndex(path); err != nil {
			return fmt.Errorf("writing index for %s: %w", path, err)
		}
		return nil
	})
}

func writeRootIndex(docsDir string) error {
	var sb strings.Builder
	sb.WriteString("# Documentation\n\n")
	fmt.Fprintf(&sb, "> Auto-generated by DocTrack on %s\n\n", time.Now().UTC().Format(time.RFC3339))
	entries, err := os.ReadDir(docsDir)
	if err != nil {
		return err
	}
	var dirs, files []string
	for _, e := range entries {
		name := e.Name()
		if strings.HasPrefix(name, ".") || name == "_index.md" {
			continue
		}
		if e.IsDir() {
			dirs = append(dirs, name)
		} else if strings.HasSuffix(name, ".md") {
			files = append(files, name)
		}
	}
	sort.Strings(dirs)
	sort.Strings(files)
	if len(dirs) > 0 {
		sb.WriteString("## Sections\n\n")
		for _, d := range dirs {
			fmt.Fprintf(&sb, "- [%s](%s/_index.md)\n", d, d)
		}
		sb.WriteString("\n")
	}
	if len(files) > 0 {
		sb.WriteString("## Files\n\n")
		for _, f := range files {
			title := strings.TrimSuffix(f, ".md")
			fmt.Fprintf(&sb, "- [%s](%s)\n", title, f)
		}
	}
	return os.WriteFile(filepath.Join(docsDir, "_index.md"), []byte(sb.String()), 0o644)
}

func writeIndex(dir string) error {
	var sb strings.Builder
	name := filepath.Base(dir)
	sb.WriteString("# " + name + "\n\n")
	fmt.Fprintf(&sb, "> Auto-generated by DocTrack on %s\n\n", time.Now().UTC().Format(time.RFC3339))
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	var dirs, files []string
	for _, e := range entries {
		n := e.Name()
		if strings.HasPrefix(n, ".") || n == "_index.md" {
			continue
		}
		if e.IsDir() {
			dirs = append(dirs, n)
		} else if strings.HasSuffix(n, ".md") {
			files = append(files, n)
		}
	}
	sort.Strings(dirs)
	sort.Strings(files)
	if len(dirs) > 0 {
		sb.WriteString("## Sections\n\n")
		for _, d := range dirs {
			fmt.Fprintf(&sb, "- [%s](%s/_index.md)\n", d, d)
		}
		sb.WriteString("\n")
	}
	if len(files) > 0 {
		sb.WriteString("## Files\n\n")
		for _, f := range files {
			title := strings.TrimSuffix(f, ".md")
			fmt.Fprintf(&sb, "- [%s](%s)\n", title, f)
		}
	}
	return os.WriteFile(filepath.Join(dir, "_index.md"), []byte(sb.String()), 0o644)
}
