// Package docs manages documentation files generated by DocTrack.
package docs

import (
	"os"
	"path/filepath"
	"strings"
)

// Mapper translates source file paths to documentation file paths.
type Mapper struct {
	docsDir string
}

// NewMapper returns a Mapper rooted at docsDir.
func NewMapper(docsDir string) *Mapper {
	return &Mapper{docsDir: docsDir}
}

// SourceToDocPath converts a relative source path to the corresponding doc path.
// Example: src/api/handler.go -> docs/api/handler.md
func (m *Mapper) SourceToDocPath(sourcePath string) string {
	clean := filepath.ToSlash(sourcePath)
	for _, prefix := range []string{"src/", "lib/", "pkg/", "app/"} {
		if strings.HasPrefix(clean, prefix) {
			clean = strings.TrimPrefix(clean, prefix)
			break
		}
	}
	ext := filepath.Ext(clean)
	base := strings.TrimSuffix(clean, ext) + ".md"
	result := filepath.Join(m.docsDir, filepath.FromSlash(base))
	// Guard against path traversal (e.g. "../" in source paths).
	absResult := filepath.Clean(result)
	absDocs := filepath.Clean(m.docsDir) + string(os.PathSeparator)
	if !strings.HasPrefix(absResult, absDocs) && absResult != filepath.Clean(m.docsDir) {
		return filepath.Join(m.docsDir, filepath.Base(base))
	}
	return result
}

// DocToSourcePath is the reverse of SourceToDocPath (best-effort).
func (m *Mapper) DocToSourcePath(docPath string) string {
	rel, err := filepath.Rel(m.docsDir, docPath)
	if err != nil {
		return docPath
	}
	clean := filepath.ToSlash(rel)
	ext := filepath.Ext(clean)
	return strings.TrimSuffix(clean, ext)
}
